---

- include_tasks: check.yml
  tags: configuration

- include_tasks: firewall.yml
  tags: firewall

- include_tasks: deps.yml
  tags: deps

- include_tasks: unattended_updates.yml
  tags: deps

- include_tasks: nginx.yml
  tags: nginx