# http://docs.ansible.com/ansible/playbooks_environment.html
# environment:
#   http_proxy: http://proxy.example.com:8080
---
- name: configure platform
  hosts: localhost
  gather_facts: False
  become: True

  vars_files:
    - "vars/main.yml"
    - "../global_vars.yml"

  pre_tasks:

    - name: configure python
      raw: sudo apt-get install python-minimal aptitude -y

    - setup:
       filter: ansible_*

    - name: set store fact
      set_fact:
        router_store_store: 'elasticsearch'
      when: CIF_ES == '1'

    - name: set build_sdist
      set_fact:
        cif_build_sdist: CIF_ANSIBLE_SDIST
      when: CIF_ANSIBLE_SDIST is defined

    - import_tasks: tasks/main.yml


  roles:
    - { role: elastic.elasticsearch,
        es_config: {
          node.data: true,
          node.master: true,
        },
        es_version: "5.4.3",
        es_instance_name: 'cif',
        when: router_store_store is defined and router_store_store == 'elasticsearch'
      }
    - { role: csirtgadgets.cif, tags: role-cif }
    - { role: nginx, tags: role-nginx }