---
- name: install EPEL
  yum: name=epel-release state=latest

- name: install deps
  yum:
    state: present
    pkg: "{{ item }}"
  with_items:
    - htop
    - git
    - "@Development Tools"
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - python-virtualenvwrapper
    - bind-utils
    - libxml2-python
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - libcurl-devel
    - net-tools
    - wget

- name: update python-dateutil
  pip: name="python-dateutil==2.4"

- name: update flask-limiter
  pip: name='Flask-Limiter>=0.9.4'

- name: work-around for requests
  pip: name="requests<2.15"