# http://docs.ansible.com/ansible/playbooks_environment.html
# environment:
#   http_proxy: http://proxy.example.com:8080
---
- name: configure platform
  hosts: localhost
  gather_facts: False
  become: True

  vars_files:
    - "vars/main.yml"
    - "../global_vars.yml"

  pre_tasks:

    - name: configure repos
      raw: rpm -iUvh http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      ignore_errors: yes

    - name: update yum
      raw: yum -y update

    - name: configure basics
      raw: yum install -y gcc python-pip python-devel git libffi-devel openssl-devel

    - setup:
       filter: ansible_*

    - name: set store fact
      set_fact:
        cif_store_store: 'elasticsearch'
      when: CIF_ES == "1"

    - import_tasks: tasks/main.yml

  roles:
    - { role: elastic.elasticsearch,
        es_config: {
          bootstrap.memory_lock: true,
          node.data: true,
          node.master: true,
        },
        when: router_store_store == 'elasticsearch'
      }
    - { role: csirtgadgets.cif, tags: role-cif }